### ISSUE TITLE
how to do streaming ogg audio?

### ISSUE THREAD

**Issue by bennyk** [iosdevzone/IDZAQAudioPlayer#4]
Dear IDZ,

I am trying to stream audio from an ogg stream like: -

http://streamer.radiocampusbruxelles.org:8000/stream.ogg

I noticed there is an assertion in the sample provided that the URL must be a file based. Any idea how I may changed the code to support streaming ogg audio?

Thanks

**Comment by DrakeWitt** [comment]
I am also trying to get an ogg stream working. One issue I'm running into is you can't really download the ogg with a NSURLConnection. Downloading it attempts to download the entire file, which never completes because it is live. How would I accomplish this? Current code:

`NSMutableURLRequest* request = [NSMutableURLRequest requestWithURL:oggUrl];
    NSURLResponse* __autoreleasing response = nil;
    NSData* data = [NSURLConnection sendSynchronousRequest:request returningResponse:&response error:&error];
    if (error) {
        NSLog(@"Unable to download audio from: %@", [oggUrl absoluteString]);
    } else {
        CFUUIDRef uuidRef = CFUUIDCreate(kCFAllocatorDefault);
        CFStringRef uuidString = CFUUIDCreateString(kCFAllocatorDefault, uuidRef);
        NSString* filePath = [NSString stringWithFormat:@"%@/%@", [NSTemporaryDirectory()stringByStandardizingPath], uuidString];
        CFRelease(uuidString);
        CFRelease(uuidRef);
        [data writeToFile:filePath atomically:YES];
        NSURL* fileURL = [NSURL fileURLWithPath:filePath];
        IDZOggVorbisFileDecoder* decoder = [[IDZOggVorbisFileDecoder alloc] initWithContentsOfURL:fileURL error:&error];
        NSLog(@"Ogg Vorbis file duration is %g", decoder.duration);
        self.player = [[IDZAQAudioPlayer alloc] initWithDecoder:decoder error:nil];
    }
`
